### ISSUE TITLE
App instantly crashes

### ISSUE THREAD

**Issue by nonetrix** [bitdust-io/android#33]
The app instantly crashes on my Google Pixel 3A running Android 12, I don't know how to get logs from a Android device so this is all I know.

**Comment by vesellov** [comment]
Hi @nonetrix ...

Did you installed the most recent version from GooglePlay Market: https://play.google.com/store/apps/details?id=org.bitdust_io.bitdust1 ? 

My testing environment is limited with my own Android S10 and I can also test on my daughter's S8...

The crush is most probably related with some newly introduced Android security features / limitations... I was not able to setup emulator for my own and that is why replying to you so long.

What you can try to do to help me finding the root cause of the issue is to enabled USB debugging on your phone and connect it to MacOs or Linux machine. Then you can use  Android Debug Bridge to get real-time logs from your phone: https://wiki.lineageos.org/adb_fastboot_guide

For me personally this works quite well:

```
adb logcat | grep -E "python|Bitdustnode|PythonActivity|BitDust|SDL|PythonService|crush|bitdust|Exception"
```

If you will be able to capture the crushing fragment from your phone and post it here It will help a lot @nonetrix  !

By the way... the work-in-progress version of BitDust Android app was moved to this repo: https://github.com/bitdust-io/p2p-app

**Comment by nonetrix** [comment]
The GitHub release works but is stuck at starting, the Google Play store version still crashes.

I broke my Linux install trying to install novideo drivers once again so I'll get back to you, if I don't respond just feel free to remind me I probably forgot.

**Comment by vesellov** [comment]
Hello again @nonetrix .

I was able to migrate the app to Android API ver. 30. Uploaded the fresh APK version 1.1.12 to Google Play and also to the GitHub releases: https://github.com/bitdust-io/p2p-app/releases/tag/alpha

Not sure if this would help to solve issue on Android 12 systems, but you could just try it.

If it still crashes then I need to find some way to test it inside emulator...

**Comment by vesellov** [comment]
Actually I was also able to build it for API level 31 which suppose to be exactly what Android 12 is based on: https://en.wikipedia.org/wiki/Android_version_history#Android_12

So I really hope it works now, @nonetrix  ....

**Comment by nonetrix** [comment]
I will try but I think that makes devices on lower API versions not work, only like 0.000000000000000000000000000000000001% of devices are that up to date

**Comment by nonetrix** [comment]
Now I get "There was a problem parsing the package."

**Comment by vesellov** [comment]
Hm... this is very strange. Just tested the .APK file downloaded from the bitdust.io web site on my phone. Could be that you need to enabled "Allow installation of apps from unknown sources" in your security settings?

Otherwise try to install from Google Play Market?  Can't imagine it fails like that from the main Google Market Store

**Comment by vesellov** [comment]
found few other tips in that article: https://www.fixcrunch.com/android-problem/there-was-a-problem-parsing-the-package/

Can be also clearing cookies and cache for Play Store may help...

**Comment by vesellov** [comment]
Hey @nonetrix ... I think i found the trouble. It was an issue in the startup stage when app is requesting a storage permissions for the first time. And also I was able to run it inside Android emulator on my Ubuntu!

Also I believe you are right about API level 31 - it is too early to use it. So I built it for API level 30 and uploaded to Google. Also was able to build it for x86_64 platforms. ;)

**Comment by nonetrix** [comment]
Even API 30 is a bit extreme, I would suggest building it where it at least works on 6.0 marshmallow(API 23)

If you set it to API 30 it means only phones running the very bleeding edge versions of Android will work. this would be fine if every phone was up to date, but this isn't the case at all unfortunately many devices still run 3+ year old versions of Android and by extension APIs

Honestly I would even experiment with lower if possible, the lower the better! If you don't need newer API features their absolutely no reason not to really

**Comment by vesellov** [comment]
I would love to do that, @nonetrix ... but unfortunately:

https://support.google.com/googleplay/android-developer/answer/9859152?visit_id=637740423371678571-866957829&rd=1#targetsdk&zippy=%2Ctarget-api-level-requirements-for-play-console

_**Starting 1 November 2021, updates to apps and games on Google Play will be required to target Android 11 (API level 30) or higher. After this date, you won't be able to upload new app bundles and APKs with a targetSdkVersion less than 30.**_

**Comment by vesellov** [comment]
I did not update my Android S10 phone to the latest OS and it perfectly runs .APK which I constructed with target API level 31... I believe it is backward compatible - old phones can still run apps built with modern API levels...

**Comment by nonetrix** [comment]
Ok sorry misunderstanding I think

**Comment by nonetrix** [comment]
Everything is fine now
